version: "3.9"

services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
  
  file-db:
    image: postgres:16
    container_name: file-db
    environment:
      POSTGRES_USER: file_user
      POSTGRES_PASSWORD: file_pass
      POSTGRES_DB: file_db
    ports:
      - "5434:5432"
    volumes:
      - file_db_data:/var/lib/postgresql/data

  file-service:
    build: ./file-service
    container_name: file-service
    environment:
      DATABASE_URL: postgresql+psycopg2://file_user:file_pass@file-db:5432/file_db
      # runtime email settings (values come from .env)
      EMAIL_RATE_LIMIT_SECONDS: ${EMAIL_RATE_LIMIT_SECONDS}
      ENABLE_RUNTIME_EMAILS: ${ENABLE_RUNTIME_EMAILS}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      RUNTIME_EMAIL_TO: ${RUNTIME_EMAIL_TO}
      EMAIL_FROM: ${EMAIL_FROM}
    depends_on:
      - file-db
    ports:
      - "5002:5002"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      DATABASE_URL: postgresql+psycopg2://auth_user:auth_pass@auth-db:5432/auth_db

      EMAIL_RATE_LIMIT_SECONDS: ${EMAIL_RATE_LIMIT_SECONDS}
      EMAIL_RATE_LIMIT_SECONDS_FAILED: ${EMAIL_RATE_LIMIT_SECONDS_FAILED}
      ENABLE_RUNTIME_EMAILS: ${ENABLE_RUNTIME_EMAILS}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      RUNTIME_EMAIL_TO: ${RUNTIME_EMAIL_TO}
      EMAIL_FROM: ${EMAIL_FROM}

    depends_on:
      - auth-db
    ports:
      - "5000:5000"


  ui-gateway:
    build: ./ui-gateway
    container_name: ui-gateway
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - file-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
    - grafana_data:/var/lib/grafana

volumes:
  auth_db_data:
  file_db_data:
  grafana_data:
