version: "3.9"

services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
  
  file-db:
    image: postgres:16
    container_name: file-db
    environment:
      POSTGRES_USER: file_user
      POSTGRES_PASSWORD: file_pass
      POSTGRES_DB: file_db
    ports:
      - "5434:5432"
    volumes:
      - file_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
  file_db_data:
